"""empty message

Revision ID: 9d0128fe5102
Revises: 
Create Date: 2018-02-02 20:02:05.979011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0128fe5102'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_devise_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devises_request_devise_id'), 'devises', ['request_devise_id'], unique=True)
    op.create_table('time_stamps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['devise_id'], ['devises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_stamps')
    op.drop_index(op.f('ix_devises_request_devise_id'), table_name='devises')
    op.drop_table('devises')
    # ### end Alembic commands ###
