"""empty message

Revision ID: d277fac6373d
Revises: 9d0128fe5102
Create Date: 2018-02-02 20:19:56.955168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd277fac6373d'
down_revision = '9d0128fe5102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_stamps', sa.Column('ping_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_stamps', 'ping_at')
    # ### end Alembic commands ###
